name: emp_details
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  sembast: ^3.1.0+2
  path_provider: ^2.0.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.1.0
  pull_to_refresh: ^2.0.0
  keyboard_dismisser: ^2.0.0
  maps_launcher: ^2.0.1
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/logo/logo.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#F7F7FF"
  image: assets/logo/splash.png
  android: true
  ios: true
  color_dark: "#F7F7FF"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/